### ISSUE TITLE
PC style Home and Delete Key

### ISSUE THREAD

**Issue by tjohnson1010** [mbaltaks/doublecommand#14]
For most development tools on Windows, Home key actually goes to the first non-white character on the line.  The current option in DoubleCommand goes to the beginning of line even if it's a tab (or any other white space character).

**Comment by mbaltaks** [comment]
This is really an application level feature, it's beyond the scope of what DoubleCommand could do. You might be able to map Command+(left cursor arrow) to do something different to the default in a specific app to achieve the desired result.
