### ISSUE TITLE
OS Mavericks 

### ISSUE THREAD

**Issue by cranmer** [mbaltaks/doublecommand#16]
DoubleCommand is not working for me on Mavericks.  
I really miss it and hope that it can be patched.

Thanks!

**Comment by bruno40gr** [comment]
Same here... miss it.

**Comment by larham** [comment]
note: in mavericks, for modifier keys (option/command/control etc.) there is built-in mapping support per keyboard in the Keyboards pref panel

**Comment by bruno40gr** [comment]
Thanks Larry.  Overlooked the new dropdown menu from which you can select your USB Keyboard and modify the keys. Restarted the receiver and now works like a charm!

**Comment by Antor** [comment]
Well, there is one thing that I really missing without DoubleCommand - its option "PC style Home and End Keys". It's really very useful and it seems like there are no good alternative solution that works as well as DoubleCommand

**Comment by cranmer** [comment]
Thanks iarham.  It seems that they pref panel does not allow separation of left and right side modifier keys.

My main issue is that I want to use the right option key (next to right Command key) as a control.  
I do this b/c I like to do ^a and ^e for beginning/end of line and that is very awkward with the left side control since a and e are also on the left.

**Comment by mbaltaks** [comment]
There is now a Mac OS X 10.9 (Mavericks) compatible DoubleCommand 1.7 released, at http://doublecommand.sourceforge.net/

**Comment by larham** [comment]
"Doublecommand-17.pkg" can't be opened because it is from an unidentified developer

In any announcement, you may want to add a link for install instructions like http://www.wikihow.com/Install-Software-from-Unsigned-Developers-on-a-Mac

**Comment by mbaltaks** [comment]
@larham thanks for reporting that, that's a handy link to keep around.

**Comment by cranmer** [comment]
This version 1.7 was working fine on Mavericks, but I just got a new macbook pro with OS X 10.9.2 and now it looses the settings on sleep/wake. If I reinstall it works, but I have to do it a lot.

I don't see DoubleCommand.crashed  in /var/tmp

Similar problem reported here:
http://forums.macrumors.com/showthread.php?t=1698203

**Comment by cranmer** [comment]
I have switched the security & privacy settings, but it doesn't solve the problem that DoubleCommand stops working after sleep/wake (not every time, have not identified a pattern). 

I have had to reinstall DoubleCommand about 20 times now.

**Comment by seance** [comment]
I also have the sleep/wake problem with Mavericks. Changing Security & Privacy does not help, and while reinstalling does, that is pretty suboptimal. Hope this problem can be solved quickly!

**Comment by chadupton** [comment]
I ended up switching to another program called KeyRemap4MacBook. It does work with mavericks and has even more options.

**Comment by danydev** [comment]
yeah, same problem here, just switched to KeyRemap4MacBook (it allows the Home\End PC Style keys)
