### ISSUE TITLE
Mojave / Catalina port

### ISSUE THREAD

**Issue by tobsn** [mbaltaks/doublecommand#28]
Will this ever happen? Any plans?

Asking because Karabiner has issues with sleep/wakeup kernel panic...
A simple fn/ctrl switch would be amazing.

Thanks!

**Comment by mbaltaks** [comment]
To be honest, right now I personally don't have the time

**Comment by tobsn** [comment]
@mbaltaks aw :/ well, know that your little app made a bunch of people happy :)

closing comment
