### ISSUE TITLE
Disables keyboard in OS X 10.6.6 (32bit)

### ISSUE THREAD

**Issue by todated** [mbaltaks/doublecommand#5]
Was using KeyRemap4MacBook previously. Disabled all of it's options to prevent any potential conflict. DoubleCommand installed fine, but then completely disabled the keyboard. Switching to the guest user, rebooting, and disabling all DoubleCommand options from the PrefPane made no difference. I had to use the Mac Keyboard Viewer with the mouse to search the web for a solution and mouse-type them into a terminal in order to uninstall, as not a single key on the physical keyboard was enabled. I was not able to determine if the conflict was with KeyRemap4MacBook.

**Comment by mbaltaks** [comment]
Just to note this here, you can open /Library/StartupItems/DoubleCommand, and then double click the uninstall.command script, and then you only need to type your password.

I expect KeyRemap4MacBook and DoubleCommand do not work together, the best bet is to remove one before trying the other.
